### ISSUE TITLE
Traceback (most recent call last):   File "OBUclientTCP.py", line 14, in <module>     sender.send_image(client_name,image)   File "/home/ubuntu/.local/lib/python3.8 if image.flags['C_CONTIGUOUS']: AttributeError: 'tuple' object has no attribute 'flags'

### ISSUE THREAD

**Issue by tkasidakis** [jeffbass/imagezmq#68]
Traceback (most recent call last):
  File "OBUclientTCP.py", line 14, in <module>
    sender.send_image(client_name,image)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/imagezmq/imagezmq.py", line 106, in send_image_reqrep
    if image.flags['C_CONTIGUOUS']:
AttributeError: 'tuple' object has no attribute 'flags'

Hello to everyone. I am trying the basic  example and i receive this in my code.
Any help ?

**Comment by jeffbass** [comment]
It is hard to tell from the traceback exactly why image is a tuple. It should be an openCV image (a numpy array). Can you provide a little more information on what example program set you were running?
Jeff
